<?php

/**
 * @file
 * Hides the comment subject if the "Allow comment title" checkbox is
 * unchecked for that node type.
 */

/**
 * Implements hook_preprocess_HOOK() for a comment.
 */
function comment_hide_subject_preprocess_comment(&$variables) {
  $node_type = $variables['node']->type;
  $subject_enabled = variable_get('comment_subject_field_' . $node_type, 0);
  
  if (!$subject_enabled) {
    // Don't display the comment title.
    $variables['title_attributes_array']['class'][] = 'element-invisible';
  }
}


function comment_hide_subject_form_alter(&$form, $form_state, $form_id) {
  // CHANGE number of post per comment form element
  if ($form_id == 'node_type_form' && isset($form['identity']['type'])) {
    $form['comment']['comment_default_per_page']['#options'] = comment_hide_subject_comment_per_page();
  }
}
function comment_hide_subject_comment_per_page() {
  return drupal_map_assoc(array(2, 5, 10, 15, 20, 25, 30, 40, 50, 70, 90, 150, 200, 250, 300));
}
