<?php
/**
 *  * Implements hook_block_info().
 *   */
function rnp_cubo_block_info() {
  $blocks['teste'] = array(
    // The name that will appear in the block list.
    'info' => 'Cubo',
    // Default setting.
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/* function teste_block_view($delta = '') { */
/*   return  $block['content'] = '<strong>teste</strong>'; */
/* } */

/* function teste_block_view($delta = '') { */
/*     return $block['content'] = array('<strong>teste</strong>'); */
/* } */

function rnp_cubo_block_view() {
  $block = array();
  $block['content'] = theme('rnp_cubo-theme');
  return $block;
}

function rnp_cubo_theme($existing, $type, $theme, $path) {
  return array(
    'rnp_cubo-theme' => array(
      'template' => 'html-page'
    ),
  );
}

function rnp_cubo_menu() {
  $items = array();
  $items['books'] = array(
    'title'             =>  'Books View',  //page title
    'description'       =>  'Books Information',  //description show when mouse hover on link
    'page callback'     =>  'books_list',  //callback function which is invoked when menu item is called.
    'access callback'   =>  true,  //any user can access this page
  );
  return $items;
}

function rnp_cubo_help($path, $arg) {
  switch ($path) {
      case "admin/help#cubo_teste":
        return t("Displays links to nodes created on this date");
        break;
    }
}

